#!/sbin/openrc-run
supervisor=supervise-daemon

name="Dagu"
description="Lightweight, powerful workflow engine with Web UI"

: ${command_user:="dagu:dagu"}

command="/usr/bin/dagu"
command_args="start-all"

depend() {
	need net
	after firewall
}

start_pre() {
	checkpath -d -m 0755 -o $command_user /etc/dagu.d
	checkpath -d -m 0755 -o $command_user /var/lib/dagu
	checkpath -d -m 0755 -o $command_user /var/log/dagu
}
