# It is possible to have the LACT daemon running on one machine, and then manage it remotely from another.
# This is disabled by default, as the TCP connection does not have any authentication or encryption mechanism!
# Make sure to only use it in trusted networks and/or set up appropriate firewall rules.
# To enable it, edit /etc/lact/config.yaml and add tcp_listen_address with your desired address
# and in the daemon section.

# daemon:
#   tcp_listen_address: 0.0.0.0:12853
#   log_level: info
#   admin_group: wheel
#   disable_clocks_cleanup: false
