#!/sbin/openrc-run

name="krill"
description="RPKI Certificate Authority and Publication Server written in Rust"

: "${command_user:="<USER>"}"

command="/usr/sbin/<SERVICE>"
: "${command_args:="--default-args"}"
command_background="yes"
pidfile="/run/$RC_SVCNAME.pid"

depend() {
	need net
	after firewall
}

# https://krill.docs.nlnetlabs.nl/en/stable/building-from-source.html#start-and-stop-the-daemon
start() {
}

stop() {
}