#!/sbin/openrc-run

name="krill"
description="RPKI Certificate Authority and Publication Server written in Rust"

: ${command_user:=krill}
: ${data_dir:=/var/lib/krill}
: ${cfgfile:=/etc/krill/krill.conf}

command="/usr/bin/krill"
command_args="-c $cfgfile server"
command_background="yes"

pidfile="/run/$RC_SVCNAME.pid"

required_files="$cfgfile"

depend() {
	need net
	after firewall
}

# https://krill.docs.nlnetlabs.nl/en/stable/building-from-source.html#start-and-stop-the-daemon
start() {
}

stop() {
}
