#!/sbin/openrc-run

name="krill"
description="RPKI Certificate Authority and Publication Server written in Rust"

: "${command_user:=krill}"
: "${data_dir:=/var/lib/krill}"
: "${log_dir:=/var/log/krill}"
: "${cfgfile:=/etc/krill/krill.conf}"

command="/usr/bin/krill"
command_args="-c $cfgfile >$log_dir/krill.log 2>&1"
command_background="yes"

pidfile="/run/$RC_SVCNAME.pid"

required_files="$cfgfile"

depend() {
	use logger dns
	need net
	after firewall
}

start_pre() {
	checkpath -d -o $command_user "$data_dir"
	checkpath -d -o $command_user "$log_dir"
	checkpath -f -o $command_user "$cfgfile"
}
