#!/sbin/openrc-run
# Copyright 2023-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 or version 3

# From: https://github.com/libimobiledevice/usbmuxd/pull/227/

name="USB multiplexing daemon"
description="Socket daemon for the usbmux protocol used by Apple devices"
command="/usr/sbin/usbmuxd"
command_args="--user usbmux"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	keyword -stop
}
